version: '2'

services:

  pweb51018023_php:
    image: 'bitnami/php-fpm:latest'
    networks:
      - net1
      - net2
    container_name: pweb51018023_php
    volumes:
      - ~/pweb201/srv4/html:/app
    labels:
      - traefik.enable=false
    restart: always

  pweb51018023:
    image: 'bitnami/nginx:latest'
    networks:
      - net1
      - net2
    container_name: pweb51018023
    volumes:
      - ~/pweb201/srv4/myapp.conf:/opt/bitnami/nginx/conf/server_blocks/myapp.conf
      - ~/pweb201/srv4/html:/app
    labels:
      - traefik.enable=true
      - traefik.backend=51018023.p-web.local
      - traefik.frontend.rule=Host:51018023.p-web.local
      - traefik.docker.network=net1
      - traefik.port=8080
    depends_on:
      - pweb51018023_php
    restart: always

networks:
  net1:
    external: true
  net2:
    external: true
